export default {
  "login": "YuShato",
  "id": 59236891,
  "node_id": "MDQ6VXNlcjU5MjM2ODkx",
  "avatar_url": "https://avatars.githubusercontent.com/u/59236891?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/YuShato",
  "html_url": "https://github.com/YuShato",
  "followers_url": "https://api.github.com/users/YuShato/followers",
  "following_url": "https://api.github.com/users/YuShato/following{/other_user}",
  "gists_url": "https://api.github.com/users/YuShato/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/YuShato/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/YuShato/subscriptions",
  "organizations_url": "https://api.github.com/users/YuShato/orgs",
  "repos_url": "https://api.github.com/users/YuShato/repos",
  "events_url": "https://api.github.com/users/YuShato/events{/privacy}",
  "received_events_url": "https://api.github.com/users/YuShato/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Yuliya Shatokhina",
  "company": null,
  "blog": "",
  "location": "Moscow",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 28,
  "public_gists": 0,
  "followers": 0,
  "following": 1,
  "created_at": "2019-12-25T22:11:17Z",
  "updated_at": "2021-11-14T22:32:49Z"
};
